packages:
  - packages/*

catalogs:
  default:
    '@astrojs/check': ^0.9.0
    '@eslint/js': ^9.0.0
    '@jscutlery/semver': ^5.3.1
    '@nx/eslint': ^21.6.10
    '@nx/eslint-plugin': ^21.6.10
    '@nx/jest': ^21.6.10
    '@nx/js': ^21.6.10
    '@nxtensions/astro': ^19.0.1
    '@swc-node/register': ~1.9.1
    '@swc/core': ~1.5.7
    '@swc/helpers': ~0.5.11
    '@testing-library/jest-dom': ^6.6.0
    '@testing-library/react': ^16.0.0
    '@testing-library/user-event': ^14.5.0
    '@types/jest': ^29.5.0
    '@types/node': ^24.0.0
    '@types/react': ^19.0.0
    '@types/react-dom': ^19.0.0
    astro: ^6.0.0
    eslint: ^9.0.0
    jest: ^29.5.0
    jest-environment-jsdom: ^29.7.0
    nx: ^21.6.10
    prettier: ^2.6.2
    react: ^19.0.0
    react-dom: ^19.0.0
    tailwindcss: ^4.0.0
    ts-jest: ^29.1.0
    ts-node: ^10.9.0
    tslib: ^2.3.0
    typescript: ^5.4.0
    typescript-eslint: ^8.0.0

allowBuilds:
  '@swc/core': true
  nx: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@swc/core'
  - nx
  - unrs-resolver
